"use server";

import crypto from "crypto";
import { revalidatePath } from "next/cache";
import { headers } from "next/headers";
import { AuditAction } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/current-user";
import { AuditEntity, logAudit } from "@/lib/audit";
import { buildPermitStoragePath, uploadToStorage } from "@/lib/supabase-storage";
import { checkRateLimit, getRequestIp } from "@/lib/rate-limit";

const DEFAULT_TTL_HOURS = 48;
const MAX_FILE_SIZE_BYTES = 25 * 1024 * 1024;

function generateToken(): string {
  // 24 bytes → 32 chars in base64url. Cryptographically random.
  return crypto.randomBytes(24).toString("base64url");
}

function buildPublicUrl(token: string): string {
  const base = process.env.NEXT_PUBLIC_APP_URL?.trim().replace(/\/$/, "") || "";
  return base ? `${base}/m/${token}` : `/m/${token}`;
}

// Generated by admins or employees from the task row in the permit dashboard.
// Reuses an existing unexpired link for the same task so re-clicks don't
// pollute the table or invalidate links already sent.
export async function generateMagicLink(taskId: string): Promise<{
  ok: boolean;
  url?: string;
  expiresAt?: string;
  error?: string;
}> {
  let me;
  try {
    me = await requireRole(["ADMIN", "EMPLOYEE"]);
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : "אין הרשאה" };
  }

  const task = await prisma.task.findFirst({
    where: { id: taskId, deletedAt: null },
    select: { id: true, name: true, permitId: true }
  });
  if (!task) return { ok: false, error: "המשימה לא נמצאה" };

  const now = new Date();
  const existing = await prisma.magicLink.findFirst({
    where: { taskId, expiresAt: { gt: now } },
    orderBy: { createdAt: "desc" }
  });
  if (existing) {
    return {
      ok: true,
      url: buildPublicUrl(existing.token),
      expiresAt: existing.expiresAt.toISOString()
    };
  }

  const token = generateToken();
  const expiresAt = new Date(now.getTime() + DEFAULT_TTL_HOURS * 60 * 60 * 1000);

  const link = await prisma.$transaction(async (tx) => {
    const created = await tx.magicLink.create({
      data: { token, taskId, permitId: task.permitId, expiresAt }
    });
    await logAudit(tx, {
      entityType: AuditEntity.MAGIC_LINK,
      entityId: created.id,
      action: AuditAction.CREATE,
      newValue: {
        taskId,
        taskName: task.name,
        permitId: task.permitId,
        expiresAt: expiresAt.toISOString(),
        ttlHours: DEFAULT_TTL_HOURS
      },
      userId: me.id
    });
    return created;
  });

  revalidatePath(`/permits/${task.permitId}`, "layout");

  return {
    ok: true,
    url: buildPublicUrl(link.token),
    expiresAt: link.expiresAt.toISOString()
  };
}

type UploadFormState = { error: string | null; ok: boolean };

// Anonymous file upload via a magic link token. No session required. Token
// is the only authn — if it's valid and unexpired, upload proceeds.
export async function uploadViaMagicLink(
  _prev: UploadFormState,
  formData: FormData
): Promise<UploadFormState> {
  try {
    const token = String(formData.get("token") || "");
    const file = formData.get("file");
    const note = String(formData.get("note") || "").trim() || null;

    if (!token) return { error: "חסר טוקן גישה", ok: false };

    const ip = getRequestIp(await headers());
    const rl = checkRateLimit(`magic-link-upload:${ip}:${token}`, {
      limit: 15,
      windowMs: 10 * 60 * 1000
    });
    if (!rl.ok) {
      return {
        error: `יותר מדי ניסיונות העלאה. נסה שוב בעוד ${rl.retryAfterSeconds} שניות`,
        ok: false
      };
    }

    if (!(file instanceof File) || file.size === 0) {
      return { error: "יש לבחור קובץ", ok: false };
    }
    if (file.size > MAX_FILE_SIZE_BYTES) {
      return {
        error: `הקובץ גדול מ-${Math.round(MAX_FILE_SIZE_BYTES / 1024 / 1024)} MB`,
        ok: false
      };
    }

    const link = await prisma.magicLink.findUnique({
      where: { token },
      include: {
        task: {
          select: { id: true, name: true, permitId: true, deletedAt: true }
        }
      }
    });
    if (!link || !link.task) {
      return { error: "קישור הגישה לא נמצא", ok: false };
    }
    if (link.expiresAt < new Date()) {
      return {
        error: "תוקף הקישור פג. פנה להנהלה לקבלת קישור חדש.",
        ok: false
      };
    }
    if (link.task.deletedAt) {
      return { error: "המשימה אינה זמינה יותר", ok: false };
    }

    // Versioning per task — match the regular upload flow.
    let version = 1;
    const max = await prisma.document.aggregate({
      where: { taskId: link.task.id },
      _max: { version: true }
    });
    if (max._max.version) version = max._max.version + 1;

    const storagePath = buildPermitStoragePath(link.task.permitId, file.name);
    const bytes = await file.arrayBuffer();
    await uploadToStorage(bytes, storagePath, file.type || null);

    const now = new Date();
    const sourceNote = "הועלה ע״י עובד שטח דרך קישור גישה";
    const combinedNotes = note ? `${sourceNote} · ${note}` : sourceNote;

    await prisma.$transaction(async (tx) => {
      const doc = await tx.document.create({
        data: {
          permitId: link.task!.permitId,
          taskId: link.task!.id,
          fileName: file.name,
          fileUrl: storagePath,
          mimeType: file.type || null,
          sizeBytes: file.size,
          version,
          isLatestApproved: false,
          uploadedById: null, // anonymous
          notes: combinedNotes
        }
      });
      await logAudit(tx, {
        entityType: AuditEntity.DOCUMENT,
        entityId: doc.id,
        action: AuditAction.CREATE,
        newValue: {
          permitId: link.task!.permitId,
          fileName: file.name,
          version,
          taskId: link.task!.id,
          taskName: link.task!.name,
          storagePath,
          sizeBytes: file.size,
          source: "MAGIC_LINK",
          magicLinkId: link.id
        },
        userId: null // anonymous upload
      });
      await tx.magicLink.update({
        where: { id: link.id },
        data: { usedAt: now }
      });
    });

    revalidatePath(`/permits/${link.task.permitId}`, "layout");
    return { error: null, ok: true };
  } catch (e) {
    return {
      error: e instanceof Error ? e.message : "שגיאה בהעלאה",
      ok: false
    };
  }
}
